security.protocol=SSL
ssl.truststore.location=/etc/kafka/secrets/truststore.jks
ssl.truststore.password=password
ssl.keystore.location=/etc/kafka/secrets/KeyStore.jks
ssl.keystore.password=password
ssl.key.password=password
